{% macro classify_pin_city(pin) %}
case
    when upper(ltrim(rtrim({{ pin }}))) like 'A%' then 'Athol'
    when upper(ltrim(rtrim({{ pin }}))) like 'C%' then 'CoeurdAlene'
    when upper(ltrim(rtrim({{ pin }}))) like 'D%' then 'Dalton_Gardens'
    when upper(ltrim(rtrim({{ pin }}))) like 'H%' then 'Hayden'
    when upper(ltrim(rtrim({{ pin }}))) like 'V%' then 'Hayden_Lake'
    when upper(ltrim(rtrim({{ pin }}))) like 'P%' then 'Post_Falls'
    when upper(ltrim(rtrim({{ pin }}))) like 'R%' then 'Rathdrum'
    when upper(ltrim(rtrim({{ pin }}))) like 'S%' then 'Spirit_Lake'
    when upper(ltrim(rtrim({{ pin }}))) like 'X%' then 'Hauser'
    when upper(ltrim(rtrim({{ pin }}))) like 'F%' then 'Fernan Lake Village'
    when upper(ltrim(rtrim({{ pin }}))) like 'B%' then 'Bayview'
    when upper(ltrim(rtrim({{ pin }}))) like 'T%' then 'Stateline'
    when upper(ltrim(rtrim({{ pin }}))) like 'U%' and upper(ltrim(rtrim({{ pin }}))) not like 'UP%' then 'Huetter'
    when upper(ltrim(rtrim({{ pin }}))) like 'W%' then 'Worley'
    when upper(ltrim(rtrim({{ pin }}))) like 'Y%' then 'Harrison'
    when upper(ltrim(rtrim({{ pin }}))) like 'E%' then 'Business Personal Property'
    when upper(ltrim(rtrim({{ pin }}))) like 'G%' then 'Cable TV'
    when upper(ltrim(rtrim({{ pin }}))) like 'KC-%' then 'Test Parcels'
    when upper(ltrim(rtrim({{ pin }}))) like 'M%' then 'Mobile Homes'
    when upper(ltrim(rtrim({{ pin }}))) like '0%' then 'Kootenai County'
    when upper(ltrim(rtrim({{ pin }}))) like '5%' then 'Kootenai County'
    when upper(ltrim(rtrim({{ pin }}))) like '4%' then 'Kootenai County'
    when upper(ltrim(rtrim({{ pin }}))) like 'UP%' then 'Operating Property'
    when upper(ltrim(rtrim({{ pin }}))) like 'L%' then 'Float Homes'
    else 'UNKNOWN'
end
{% endmacro %}
